---
name: "First Workflow for this repo."

run-name: "first work flow triggered by ${{github.actor}} with event name: ${{github.event_name}} on branch ${{github.ref}}."
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: cat hello.txt
